// <auto-generated />
using System;
using IEManageSystem.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace IEManageSystem.Migrations
{
    [DbContext(typeof(IEManageSystemDbContext))]
    partial class IEManageSystemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("IEManageSystem.ApiAuthorization.DomainModel.ApiScopes.ApiScope", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ApiManageScopeId");

                    b.Property<int?>("ApiQueryScopeId");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ApiManageScopeId");

                    b.HasIndex("ApiQueryScopeId");

                    b.ToTable("ApiScope");
                });

            modelBuilder.Entity("IEManageSystem.ApiAuthorization.DomainModel.ApiScopes.ApiScopePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApiScopeId");

                    b.Property<int?>("ApiScopeNodeId");

                    b.Property<int>("PermissionId");

                    b.HasKey("Id");

                    b.HasIndex("ApiScopeNodeId");

                    b.HasIndex("PermissionId");

                    b.ToTable("ApiScopePermission");
                });

            modelBuilder.Entity("IEManageSystem.ApiAuthorization.DomainModel.ApiScopes.AuthorizationNodes.ApiScopeNode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("ApiScopeNode");

                    b.HasDiscriminator<string>("Discriminator").HasValue("ApiScopeNode");
                });

            modelBuilder.Entity("IEManageSystem.ApiAuthorization.DomainModel.ApiSingles.ApiSingle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApiScopeId");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ApiScopeId");

                    b.ToTable("ApiSingles");
                });

            modelBuilder.Entity("IEManageSystem.ApiAuthorization.DomainModel.ApiSingles.ApiSingleAction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ApiSingleId");

                    b.Property<bool>("IsQueryAction");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.HasIndex("ApiSingleId");

                    b.ToTable("ApiSingleAction");
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.CmsComponent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("CmsComponents");
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Menus.MenuBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompositeMenuId");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("DisplayName")
                        .IsRequired();

                    b.Property<string>("Icon");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("CompositeMenuId");

                    b.ToTable("Menus");

                    b.HasDiscriminator<string>("Discriminator").HasValue("MenuBase");
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Pages.ContentComponentData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("ContentLeafComponentId");

                    b.Property<int?>("PageDataId");

                    b.HasKey("Id");

                    b.HasIndex("ContentLeafComponentId");

                    b.HasIndex("PageDataId");

                    b.ToTable("ContentComponentData");
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Pages.PageBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("DisplayName");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Pages");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PageBase");
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Pages.PageComponentBase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CmsComponentId");

                    b.Property<string>("Col");

                    b.Property<int?>("CompositeComponentId");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Height");

                    b.Property<string>("Name");

                    b.Property<string>("Padding");

                    b.Property<int>("PageId");

                    b.Property<string>("Sign");

                    b.HasKey("Id");

                    b.HasIndex("CmsComponentId");

                    b.HasIndex("CompositeComponentId");

                    b.HasIndex("PageId");

                    b.ToTable("PageComponentBase");

                    b.HasDiscriminator<string>("Discriminator").HasValue("PageComponentBase");
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Pages.PageData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("PageBaseId");

                    b.HasKey("Id");

                    b.HasIndex("PageBaseId");

                    b.ToTable("PageData");
                });

            modelBuilder.Entity("IEManageSystem.Entitys.Authorization.Permissions.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Describe");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Permission");
                });

            modelBuilder.Entity("IEManageSystem.Entitys.Authorization.Roles.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Describe");

                    b.Property<string>("DisplayName");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("IEManageSystem.Entitys.Authorization.Roles.RolePermission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("PermissionId");

                    b.Property<int>("RoleId");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId");

                    b.ToTable("RolePermission");
                });

            modelBuilder.Entity("IEManageSystem.Entitys.Authorization.Users.Accounts.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60);

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.HasKey("Id");

                    b.ToTable("Account");
                });

            modelBuilder.Entity("IEManageSystem.Entitys.Authorization.Users.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("AccountId");

                    b.Property<string>("Address");

                    b.Property<DateTime>("BirthDate");

                    b.Property<string>("EmailAddress");

                    b.Property<string>("HeadSculpture");

                    b.Property<string>("IDNumber");

                    b.Property<string>("Name")
                        .HasMaxLength(20);

                    b.Property<string>("PersonSignature");

                    b.Property<string>("Phone");

                    b.Property<string>("RealName");

                    b.Property<bool>("Sex");

                    b.Property<int?>("TenantId");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("IEManageSystem.Entitys.Authorization.Users.UserRole", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("RoleId");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("IEManageSystem.ApiAuthorization.DomainModel.ApiScopes.AuthorizationNodes.ApiManageScope", b =>
                {
                    b.HasBaseType("IEManageSystem.ApiAuthorization.DomainModel.ApiScopes.AuthorizationNodes.ApiScopeNode");


                    b.ToTable("ApiManageScope");

                    b.HasDiscriminator().HasValue("ApiManageScope");
                });

            modelBuilder.Entity("IEManageSystem.ApiAuthorization.DomainModel.ApiScopes.AuthorizationNodes.ApiQueryScope", b =>
                {
                    b.HasBaseType("IEManageSystem.ApiAuthorization.DomainModel.ApiScopes.AuthorizationNodes.ApiScopeNode");


                    b.ToTable("ApiQueryScope");

                    b.HasDiscriminator().HasValue("ApiQueryScope");
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Menus.CompositeMenu", b =>
                {
                    b.HasBaseType("IEManageSystem.CMS.DomainModel.Menus.MenuBase");


                    b.ToTable("CompositeMenu");

                    b.HasDiscriminator().HasValue("CompositeMenu");
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Menus.LeafMenu", b =>
                {
                    b.HasBaseType("IEManageSystem.CMS.DomainModel.Menus.MenuBase");

                    b.Property<int?>("PageId");

                    b.HasIndex("PageId");

                    b.ToTable("LeafMenu");

                    b.HasDiscriminator().HasValue("LeafMenu");
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Pages.ContentPage", b =>
                {
                    b.HasBaseType("IEManageSystem.CMS.DomainModel.Pages.PageBase");


                    b.ToTable("ContentPage");

                    b.HasDiscriminator().HasValue("ContentPage");
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Pages.StaticPage", b =>
                {
                    b.HasBaseType("IEManageSystem.CMS.DomainModel.Pages.PageBase");


                    b.ToTable("StaticPage");

                    b.HasDiscriminator().HasValue("StaticPage");
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Pages.CompositeComponent", b =>
                {
                    b.HasBaseType("IEManageSystem.CMS.DomainModel.Pages.PageComponentBase");


                    b.ToTable("CompositeComponent");

                    b.HasDiscriminator().HasValue("CompositeComponent");
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Pages.ContentLeafComponent", b =>
                {
                    b.HasBaseType("IEManageSystem.CMS.DomainModel.Pages.PageComponentBase");


                    b.ToTable("ContentLeafComponent");

                    b.HasDiscriminator().HasValue("ContentLeafComponent");
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Pages.PageLeafComponent", b =>
                {
                    b.HasBaseType("IEManageSystem.CMS.DomainModel.Pages.PageComponentBase");


                    b.ToTable("PageLeafComponent");

                    b.HasDiscriminator().HasValue("PageLeafComponent");
                });

            modelBuilder.Entity("IEManageSystem.ApiAuthorization.DomainModel.ApiScopes.ApiScope", b =>
                {
                    b.HasOne("IEManageSystem.ApiAuthorization.DomainModel.ApiScopes.AuthorizationNodes.ApiManageScope", "ApiManageScope")
                        .WithMany()
                        .HasForeignKey("ApiManageScopeId");

                    b.HasOne("IEManageSystem.ApiAuthorization.DomainModel.ApiScopes.AuthorizationNodes.ApiQueryScope", "ApiQueryScope")
                        .WithMany()
                        .HasForeignKey("ApiQueryScopeId");
                });

            modelBuilder.Entity("IEManageSystem.ApiAuthorization.DomainModel.ApiScopes.ApiScopePermission", b =>
                {
                    b.HasOne("IEManageSystem.ApiAuthorization.DomainModel.ApiScopes.AuthorizationNodes.ApiScopeNode")
                        .WithMany("ApiScopePermissions")
                        .HasForeignKey("ApiScopeNodeId");

                    b.HasOne("IEManageSystem.Entitys.Authorization.Permissions.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IEManageSystem.ApiAuthorization.DomainModel.ApiSingles.ApiSingle", b =>
                {
                    b.HasOne("IEManageSystem.ApiAuthorization.DomainModel.ApiScopes.ApiScope")
                        .WithMany("ApiSingles")
                        .HasForeignKey("ApiScopeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IEManageSystem.ApiAuthorization.DomainModel.ApiSingles.ApiSingleAction", b =>
                {
                    b.HasOne("IEManageSystem.ApiAuthorization.DomainModel.ApiSingles.ApiSingle")
                        .WithMany("ApiSingleActions")
                        .HasForeignKey("ApiSingleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Menus.MenuBase", b =>
                {
                    b.HasOne("IEManageSystem.CMS.DomainModel.Menus.CompositeMenu")
                        .WithMany("Menus")
                        .HasForeignKey("CompositeMenuId");
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Pages.ContentComponentData", b =>
                {
                    b.HasOne("IEManageSystem.CMS.DomainModel.Pages.ContentLeafComponent")
                        .WithMany("ContentComponentDatas")
                        .HasForeignKey("ContentLeafComponentId");

                    b.HasOne("IEManageSystem.CMS.DomainModel.Pages.PageData")
                        .WithMany("ContentComponentDatas")
                        .HasForeignKey("PageDataId");
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Pages.PageComponentBase", b =>
                {
                    b.HasOne("IEManageSystem.CMS.DomainModel.CmsComponent", "CmsComponent")
                        .WithMany()
                        .HasForeignKey("CmsComponentId");

                    b.HasOne("IEManageSystem.CMS.DomainModel.Pages.CompositeComponent")
                        .WithMany("PageComponents")
                        .HasForeignKey("CompositeComponentId");

                    b.HasOne("IEManageSystem.CMS.DomainModel.Pages.PageBase", "Page")
                        .WithMany("PageComponents")
                        .HasForeignKey("PageId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Pages.PageData", b =>
                {
                    b.HasOne("IEManageSystem.CMS.DomainModel.Pages.PageBase")
                        .WithMany("PageDatas")
                        .HasForeignKey("PageBaseId");
                });

            modelBuilder.Entity("IEManageSystem.Entitys.Authorization.Roles.RolePermission", b =>
                {
                    b.HasOne("IEManageSystem.Entitys.Authorization.Permissions.Permission", "Permission")
                        .WithMany()
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IEManageSystem.Entitys.Authorization.Roles.Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IEManageSystem.Entitys.Authorization.Users.Accounts.Account", b =>
                {
                    b.OwnsOne("IEManageSystem.Entitys.Authorization.Users.Accounts.SafetyProblem", "SafetyProblem", b1 =>
                        {
                            b1.Property<int?>("AccountId")
                                .ValueGeneratedOnAdd()
                                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                            b1.Property<string>("Answer")
                                .HasMaxLength(20);

                            b1.Property<string>("Problem")
                                .HasMaxLength(20);

                            b1.ToTable("Account");

                            b1.HasOne("IEManageSystem.Entitys.Authorization.Users.Accounts.Account")
                                .WithOne("SafetyProblem")
                                .HasForeignKey("IEManageSystem.Entitys.Authorization.Users.Accounts.SafetyProblem", "AccountId")
                                .OnDelete(DeleteBehavior.Cascade);
                        });
                });

            modelBuilder.Entity("IEManageSystem.Entitys.Authorization.Users.User", b =>
                {
                    b.HasOne("IEManageSystem.Entitys.Authorization.Users.Accounts.Account", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId");
                });

            modelBuilder.Entity("IEManageSystem.Entitys.Authorization.Users.UserRole", b =>
                {
                    b.HasOne("IEManageSystem.Entitys.Authorization.Roles.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("IEManageSystem.Entitys.Authorization.Users.User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("IEManageSystem.CMS.DomainModel.Menus.LeafMenu", b =>
                {
                    b.HasOne("IEManageSystem.CMS.DomainModel.Pages.PageBase", "Page")
                        .WithMany()
                        .HasForeignKey("PageId");
                });
#pragma warning restore 612, 618
        }
    }
}
